### ISSUE TITLE
introduce a default tasks-file require

### ISSUE THREAD

**Issue by ezekielchentnik** [start-runner/simple-cli#1]
can we introduce a default tasks-file?  This way you don't have to specify the path when using cli in npm scripts.  Example:

project:

```
/my-project
    /src
        server.js
    tasks.js
```

npm scripts:

```
"scripts": {
    "start": "node ./src/server.js",
    "dev": "start-runner dev",  // finds task in default tasks file e.g. ./tasks.js
    "build": "start-runner build"
}
```

**Comment by deepsweet** [comment]
thanks for the idea! I'll take a look, it requires to rethink how simple-cli handle arguments.

**Comment by deepsweet** [comment]
done https://github.com/start-runner/simple-cli/releases/tag/v3.0.0

**Comment by deepsweet** [comment]
and https://github.com/start-runner/babel-cli/pull/2 is on the way.
