### ISSUE TITLE
cli returning exit code 1 

### ISSUE THREAD

**Issue by eisisig** [start-runner/simple-cli#2]
Is there really a need to return exit `process.exit(1)` from the cli when you call the runner without task? I like the idea that it lists the available tasks, as in "You didn't provide a task. Here is a list" but the error is pretty brutal IMHO :D

Took me some time to find out "what was wrong" with my setup until I looked at the source code of simple cli (was using babel-cli)

**Comment by deepsweet** [comment]
just bumped start-babel-cli too 👍
